// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.nurunuru

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_nurunuru_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_nurunuru_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_nurunuru"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}




















































































































// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib
// * IntegrityCheckingUniffiLib (this)
// we allow for ~2x as many methods in the UniffiLib interface.
//
// The `ffi_uniffi_contract_version` method and all checksum methods are put
// into `IntegrityCheckingUniffiLib` and these methods are called only once,
// when the library is loaded.
internal interface IntegrityCheckingUniffiLib : Library {
    // Integrity check functions only
    fun uniffi_nurunuru_ffi_checksum_func_npub_to_hex(
): Short
fun uniffi_nurunuru_ffi_checksum_func_parse_keys(
): Short
fun uniffi_nurunuru_ffi_checksum_func_pubkey_to_npub(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_birdwatch_post(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_connect(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_connection_stats(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_delete_event(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_disconnect(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_badges(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_dm_conversations(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_dm_messages(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_follow_list(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_profile(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_user_notes(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_follow_user(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_format_timestamp(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_get_recommended_feed(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_login(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_mark_not_interested(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_publish_note(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_record_engagement(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_request_vanish(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_search(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_send_dm(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_unfollow_user(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_verify_nip05(
): Short
fun uniffi_nurunuru_ffi_checksum_method_nurunuruclient_zap(
): Short
fun uniffi_nurunuru_ffi_checksum_constructor_nurunuruclient_new(
): Short
fun ffi_nurunuru_ffi_uniffi_contract_version(
): Int

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.
internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            val componentName = "nurunuru"
            // For large crates we prevent `MethodTooLargeException` (see #2340)
            // N.B. the name of the extension is very misleading, since it is
            // rather `InterfaceTooLargeException`, caused by too many methods
            // in the interface for large crates.
            //
            // By splitting the otherwise huge interface into two parts
            // * UniffiLib (this)
            // * IntegrityCheckingUniffiLib
            // And all checksum methods are put into `IntegrityCheckingUniffiLib`
            // we allow for ~2x as many methods in the UniffiLib interface.
            //
            // Thus we first load the library with `loadIndirect` as `IntegrityCheckingUniffiLib`
            // so that we can (optionally!) call `uniffiCheckApiChecksums`...
            loadIndirect<IntegrityCheckingUniffiLib>(componentName)
                .also { lib: IntegrityCheckingUniffiLib ->
                    uniffiCheckContractApiVersion(lib)
                    uniffiCheckApiChecksums(lib)
                }
            // ... and then we load the library as `UniffiLib`
            // N.B. we cannot use `loadIndirect` once and then try to cast it to `UniffiLib`
            // => results in `java.lang.ClassCastException: com.sun.proxy.$Proxy cannot be cast to ...`
            // error. So we must call `loadIndirect` twice. For crates large enough
            // to trigger this issue, the performance impact is negligible, running on
            // a macOS M1 machine the `loadIndirect` call takes ~50ms.
            val lib = loadIndirect<UniffiLib>(componentName)
            // No need to check the contract version and checksums, since
            // we already did that with `IntegrityCheckingUniffiLib` above.
            // Loading of library with integrity check done.
            lib
        }

        // The Cleaner for the whole library
        internal val CLEANER: UniffiCleaner by lazy {
            UniffiCleaner.create()
        }
    }

    // FFI functions
    fun uniffi_nurunuru_ffi_fn_clone_nurunuruclient(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus,
): Pointer
fun uniffi_nurunuru_ffi_fn_free_nurunuruclient(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun uniffi_nurunuru_ffi_fn_constructor_nurunuruclient_new(`secretKeyHex`: RustBuffer.ByValue,`dbPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): Pointer
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_birdwatch_post(`ptr`: Pointer,`eventIdHex`: RustBuffer.ByValue,`authorPubkeyHex`: RustBuffer.ByValue,`contextType`: RustBuffer.ByValue,`content`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_connect(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_connection_stats(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_delete_event(`ptr`: Pointer,`eventIdHex`: RustBuffer.ByValue,`reason`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_disconnect(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_badges(`ptr`: Pointer,`pubkeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_dm_conversations(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_dm_messages(`ptr`: Pointer,`partnerPubkeyHex`: RustBuffer.ByValue,`limit`: Int,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_follow_list(`ptr`: Pointer,`pubkeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_profile(`ptr`: Pointer,`pubkeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_user_notes(`ptr`: Pointer,`pubkeyHex`: RustBuffer.ByValue,`limit`: Int,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_follow_user(`ptr`: Pointer,`targetPubkeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_format_timestamp(`ptr`: Pointer,`timestamp`: Long,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_get_recommended_feed(`ptr`: Pointer,`limit`: Int,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_login(`ptr`: Pointer,`pubkeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_mark_not_interested(`ptr`: Pointer,`eventId`: RustBuffer.ByValue,`authorPubkey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_publish_note(`ptr`: Pointer,`content`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_record_engagement(`ptr`: Pointer,`action`: RustBuffer.ByValue,`authorPubkey`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_request_vanish(`ptr`: Pointer,`reason`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_search(`ptr`: Pointer,`query`: RustBuffer.ByValue,`limit`: Int,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_send_dm(`ptr`: Pointer,`recipientHex`: RustBuffer.ByValue,`content`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_unfollow_user(`ptr`: Pointer,`targetPubkeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_verify_nip05(`ptr`: Pointer,`nip05`: RustBuffer.ByValue,`pubkeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): Byte
fun uniffi_nurunuru_ffi_fn_method_nurunuruclient_zap(`ptr`: Pointer,`eventIdHex`: RustBuffer.ByValue,`authorPubkeyHex`: RustBuffer.ByValue,`amountSats`: Long,`message`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun uniffi_nurunuru_ffi_fn_func_npub_to_hex(`npub`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_func_parse_keys(`input`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun uniffi_nurunuru_ffi_fn_func_pubkey_to_npub(`pubkeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun ffi_nurunuru_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun ffi_nurunuru_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun ffi_nurunuru_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
): Unit
fun ffi_nurunuru_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun ffi_nurunuru_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_u8(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_u8(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Byte
fun ffi_nurunuru_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_i8(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_i8(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Byte
fun ffi_nurunuru_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_u16(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_u16(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Short
fun ffi_nurunuru_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_i16(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_i16(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Short
fun ffi_nurunuru_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_u32(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_u32(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Int
fun ffi_nurunuru_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_i32(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_i32(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Int
fun ffi_nurunuru_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_u64(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_u64(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Long
fun ffi_nurunuru_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_i64(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_i64(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Long
fun ffi_nurunuru_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_f32(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_f32(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Float
fun ffi_nurunuru_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_f64(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_f64(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Double
fun ffi_nurunuru_ffi_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_pointer(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_pointer(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Pointer
fun ffi_nurunuru_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_rust_buffer(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): RustBuffer.ByValue
fun ffi_nurunuru_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_cancel_void(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_free_void(`handle`: Long,
): Unit
fun ffi_nurunuru_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
): Unit

}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_nurunuru_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_nurunuru_ffi_checksum_func_npub_to_hex() != 20005.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_func_parse_keys() != 20160.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_func_pubkey_to_npub() != 11266.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_birdwatch_post() != 21370.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_connect() != 60654.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_connection_stats() != 46577.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_delete_event() != 21602.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_disconnect() != 38631.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_badges() != 27626.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_dm_conversations() != 35549.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_dm_messages() != 40440.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_follow_list() != 46391.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_profile() != 8539.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_fetch_user_notes() != 53253.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_follow_user() != 13972.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_format_timestamp() != 26250.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_get_recommended_feed() != 3279.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_login() != 56079.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_mark_not_interested() != 14317.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_publish_note() != 17434.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_record_engagement() != 57804.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_request_vanish() != 33776.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_search() != 31612.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_send_dm() != 20544.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_unfollow_user() != 42695.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_verify_nip05() != 24119.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_method_nurunuruclient_zap() != 41981.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_nurunuru_ffi_checksum_constructor_nurunuruclient_new() != 46388.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    UniffiLib.INSTANCE
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/**
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer
/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        java.lang.Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (e: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}


// This template implements a class for working with a Rust struct via a Pointer/Arc<T>
// to the live Rust struct on the other side of the FFI.
//
// Each instance implements core operations for working with the Rust `Arc<T>` and the
// Kotlin Pointer to work with the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


/**
 * NuruNuru client for iOS / Android native apps.
 *
 * Wraps nurunuru-core (nostr-sdk + nostrdb) behind a synchronous FFI
 * boundary.  All network calls block the calling thread; use background
 * threads / coroutines on the platform side.
 *
 * Lifecycle:
 *   1. Construct with the user's private key hex/nsec and a DB path.
 *   2. Call connect() to open relay WebSocket connections.
 *   3. Call login(pubkeyHex) to load follow/mute lists.
 *   4. Use feed/profile/DM/publish methods as needed.
 *   5. Call disconnect() before releasing the object.
 */
public interface NuruNuruClientInterface {

    /**
     * Create a Birdwatch label for an event.
     */
    fun `birdwatchPost`(`eventIdHex`: kotlin.String, `authorPubkeyHex`: kotlin.String, `contextType`: kotlin.String, `content`: kotlin.String): kotlin.String

    /**
     * Connect to all default Japanese Nostr relays.
     */
    fun `connect`()

    /**
     * Get relay pool connection statistics.
     */
    fun `connectionStats`(): FfiConnectionStats

    /**
     * Delete an event.
     */
    fun `deleteEvent`(`eventIdHex`: kotlin.String, `reason`: kotlin.String?): kotlin.String

    /**
     * Disconnect from all relays.
     */
    fun `disconnect`()

    /**
     * Fetch earned badges for a user.
     */
    fun `fetchBadges`(`pubkeyHex`: kotlin.String): List<FfiBadgeAward>

    /**
     * Fetch all DM conversations.
     */
    fun `fetchDmConversations`(): List<FfiDmConversation>

    /**
     * Fetch messages in a conversation.
     */
    fun `fetchDmMessages`(`partnerPubkeyHex`: kotlin.String, `limit`: kotlin.UInt): List<FfiDmMessage>

    /**
     * Fetch the follow list for a user. Returns pubkey hex strings.
     */
    fun `fetchFollowList`(`pubkeyHex`: kotlin.String): List<kotlin.String>

    /**
     * Fetch a user's profile (kind 0 metadata event).
     * Returns null if no profile is found within the timeout.
     */
    fun `fetchProfile`(`pubkeyHex`: kotlin.String): FfiUserProfile?

    /**
     * Fetch recent notes from a specific user.
     */
    fun `fetchUserNotes`(`pubkeyHex`: kotlin.String, `limit`: kotlin.UInt): List<FfiScoredPost>

    /**
     * Follow a user (publishes updated kind 3 contact list).
     */
    fun `followUser`(`targetPubkeyHex`: kotlin.String)

    /**
     * Format a Unix timestamp as a Japanese relative string
     * (e.g. "たった今", "3分", "2時間", "5日", "3月14日").
     */
    fun `formatTimestamp`(`timestamp`: kotlin.ULong): kotlin.String

    /**
     * Get a ranked feed (X-algorithm). Returns scored posts.
     */
    fun `getRecommendedFeed`(`limit`: kotlin.UInt): List<FfiScoredPost>

    /**
     * Set the active user and load their follow/mute lists from relays.
     */
    fun `login`(`pubkeyHex`: kotlin.String)

    /**
     * Mark a post as "not interested" (lowers author's score).
     */
    fun `markNotInterested`(`eventId`: kotlin.String, `authorPubkey`: kotlin.String)

    /**
     * Publish a plain text note (kind 1). Returns the event ID hex.
     */
    fun `publishNote`(`content`: kotlin.String): kotlin.String

    /**
     * Record an engagement action ("like", "repost", "reply") for
     * personalizing future feed rankings.
     */
    fun `recordEngagement`(`action`: kotlin.String, `authorPubkey`: kotlin.String)

    /**
     * Request to vanish (IRREVERSIBLE).
     */
    fun `requestVanish`(`reason`: kotlin.String?): kotlin.String

    /**
     * Full-text search. Returns matching event ID hex strings.
     */
    fun `search`(`query`: kotlin.String, `limit`: kotlin.UInt): List<kotlin.String>

    /**
     * Send an encrypted DM via NIP-17 gift wrapping.
     */
    fun `sendDm`(`recipientHex`: kotlin.String, `content`: kotlin.String)

    /**
     * Unfollow a user (publishes updated kind 3 contact list).
     */
    fun `unfollowUser`(`targetPubkeyHex`: kotlin.String)

    /**
     * Verify NIP-05 identifier.
     */
    fun `verifyNip05`(`nip05`: kotlin.String, `pubkeyHex`: kotlin.String): kotlin.Boolean

    /**
     * Zap a user's post.
     */
    fun `zap`(`eventIdHex`: kotlin.String, `authorPubkeyHex`: kotlin.String, `amountSats`: kotlin.ULong, `message`: kotlin.String?)

    companion object
}

/**
 * NuruNuru client for iOS / Android native apps.
 *
 * Wraps nurunuru-core (nostr-sdk + nostrdb) behind a synchronous FFI
 * boundary.  All network calls block the calling thread; use background
 * threads / coroutines on the platform side.
 *
 * Lifecycle:
 *   1. Construct with the user's private key hex/nsec and a DB path.
 *   2. Call connect() to open relay WebSocket connections.
 *   3. Call login(pubkeyHex) to load follow/mute lists.
 *   4. Use feed/profile/DM/publish methods as needed.
 *   5. Call disconnect() before releasing the object.
 */
open class NuruNuruClient: Disposable, AutoCloseable, NuruNuruClientInterface
{

    constructor(pointer: Pointer) {
        this.pointer = pointer
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }

    /**
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noPointer: NoPointer) {
        this.pointer = null
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }
    /**
     * Create a new client.
     * `secret_key_hex` — hex private key or nsec Bech32.
     * `db_path`        — directory for the local nostrdb (LMDB) cache.
     */
    constructor(`secretKeyHex`: kotlin.String, `dbPath`: kotlin.String) :
        this(
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_constructor_nurunuruclient_new(
        FfiConverterString.lower(`secretKeyHex`),FfiConverterString.lower(`dbPath`),_status)
}
    )

    protected val pointer: Pointer?
    protected val cleanable: UniffiCleaner.Cleanable

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.uniffiClonePointer())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_free_nurunuruclient(ptr, status)
                }
            }
        }
    }

    fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_clone_nurunuruclient(pointer!!, status)
        }
    }


    /**
     * Create a Birdwatch label for an event.
     */
    @Throws(NuruNuruFfiException::class)override fun `birdwatchPost`(`eventIdHex`: kotlin.String, `authorPubkeyHex`: kotlin.String, `contextType`: kotlin.String, `content`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_birdwatch_post(
        it, FfiConverterString.lower(`eventIdHex`),FfiConverterString.lower(`authorPubkeyHex`),FfiConverterString.lower(`contextType`),FfiConverterString.lower(`content`),_status)
}
    }
    )
    }



    /**
     * Connect to all default Japanese Nostr relays.
     */override fun `connect`()
        =
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_connect(
        it, _status)
}
    }




    /**
     * Get relay pool connection statistics.
     */override fun `connectionStats`(): FfiConnectionStats {
            return FfiConverterTypeFfiConnectionStats.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_connection_stats(
        it, _status)
}
    }
    )
    }



    /**
     * Delete an event.
     */
    @Throws(NuruNuruFfiException::class)override fun `deleteEvent`(`eventIdHex`: kotlin.String, `reason`: kotlin.String?): kotlin.String {
            return FfiConverterString.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_delete_event(
        it, FfiConverterString.lower(`eventIdHex`),FfiConverterOptionalString.lower(`reason`),_status)
}
    }
    )
    }



    /**
     * Disconnect from all relays.
     */
    @Throws(NuruNuruFfiException::class)override fun `disconnect`()
        =
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_disconnect(
        it, _status)
}
    }




    /**
     * Fetch earned badges for a user.
     */
    @Throws(NuruNuruFfiException::class)override fun `fetchBadges`(`pubkeyHex`: kotlin.String): List<FfiBadgeAward> {
            return FfiConverterSequenceTypeFfiBadgeAward.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_badges(
        it, FfiConverterString.lower(`pubkeyHex`),_status)
}
    }
    )
    }



    /**
     * Fetch all DM conversations.
     */
    @Throws(NuruNuruFfiException::class)override fun `fetchDmConversations`(): List<FfiDmConversation> {
            return FfiConverterSequenceTypeFfiDmConversation.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_dm_conversations(
        it, _status)
}
    }
    )
    }



    /**
     * Fetch messages in a conversation.
     */
    @Throws(NuruNuruFfiException::class)override fun `fetchDmMessages`(`partnerPubkeyHex`: kotlin.String, `limit`: kotlin.UInt): List<FfiDmMessage> {
            return FfiConverterSequenceTypeFfiDmMessage.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_dm_messages(
        it, FfiConverterString.lower(`partnerPubkeyHex`),FfiConverterUInt.lower(`limit`),_status)
}
    }
    )
    }



    /**
     * Fetch the follow list for a user. Returns pubkey hex strings.
     */
    @Throws(NuruNuruFfiException::class)override fun `fetchFollowList`(`pubkeyHex`: kotlin.String): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_follow_list(
        it, FfiConverterString.lower(`pubkeyHex`),_status)
}
    }
    )
    }



    /**
     * Fetch a user's profile (kind 0 metadata event).
     * Returns null if no profile is found within the timeout.
     */
    @Throws(NuruNuruFfiException::class)override fun `fetchProfile`(`pubkeyHex`: kotlin.String): FfiUserProfile? {
            return FfiConverterOptionalTypeFfiUserProfile.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_profile(
        it, FfiConverterString.lower(`pubkeyHex`),_status)
}
    }
    )
    }



    /**
     * Fetch recent notes from a specific user.
     */
    @Throws(NuruNuruFfiException::class)override fun `fetchUserNotes`(`pubkeyHex`: kotlin.String, `limit`: kotlin.UInt): List<FfiScoredPost> {
            return FfiConverterSequenceTypeFfiScoredPost.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_fetch_user_notes(
        it, FfiConverterString.lower(`pubkeyHex`),FfiConverterUInt.lower(`limit`),_status)
}
    }
    )
    }



    /**
     * Follow a user (publishes updated kind 3 contact list).
     */
    @Throws(NuruNuruFfiException::class)override fun `followUser`(`targetPubkeyHex`: kotlin.String)
        =
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_follow_user(
        it, FfiConverterString.lower(`targetPubkeyHex`),_status)
}
    }




    /**
     * Format a Unix timestamp as a Japanese relative string
     * (e.g. "たった今", "3分", "2時間", "5日", "3月14日").
     */override fun `formatTimestamp`(`timestamp`: kotlin.ULong): kotlin.String {
            return FfiConverterString.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_format_timestamp(
        it, FfiConverterULong.lower(`timestamp`),_status)
}
    }
    )
    }



    /**
     * Get a ranked feed (X-algorithm). Returns scored posts.
     */
    @Throws(NuruNuruFfiException::class)override fun `getRecommendedFeed`(`limit`: kotlin.UInt): List<FfiScoredPost> {
            return FfiConverterSequenceTypeFfiScoredPost.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_get_recommended_feed(
        it, FfiConverterUInt.lower(`limit`),_status)
}
    }
    )
    }



    /**
     * Set the active user and load their follow/mute lists from relays.
     */
    @Throws(NuruNuruFfiException::class)override fun `login`(`pubkeyHex`: kotlin.String)
        =
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_login(
        it, FfiConverterString.lower(`pubkeyHex`),_status)
}
    }




    /**
     * Mark a post as "not interested" (lowers author's score).
     */override fun `markNotInterested`(`eventId`: kotlin.String, `authorPubkey`: kotlin.String)
        =
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_mark_not_interested(
        it, FfiConverterString.lower(`eventId`),FfiConverterString.lower(`authorPubkey`),_status)
}
    }




    /**
     * Publish a plain text note (kind 1). Returns the event ID hex.
     */
    @Throws(NuruNuruFfiException::class)override fun `publishNote`(`content`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_publish_note(
        it, FfiConverterString.lower(`content`),_status)
}
    }
    )
    }



    /**
     * Record an engagement action ("like", "repost", "reply") for
     * personalizing future feed rankings.
     */override fun `recordEngagement`(`action`: kotlin.String, `authorPubkey`: kotlin.String)
        =
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_record_engagement(
        it, FfiConverterString.lower(`action`),FfiConverterString.lower(`authorPubkey`),_status)
}
    }




    /**
     * Request to vanish (IRREVERSIBLE).
     */
    @Throws(NuruNuruFfiException::class)override fun `requestVanish`(`reason`: kotlin.String?): kotlin.String {
            return FfiConverterString.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_request_vanish(
        it, FfiConverterOptionalString.lower(`reason`),_status)
}
    }
    )
    }



    /**
     * Full-text search. Returns matching event ID hex strings.
     */
    @Throws(NuruNuruFfiException::class)override fun `search`(`query`: kotlin.String, `limit`: kotlin.UInt): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_search(
        it, FfiConverterString.lower(`query`),FfiConverterUInt.lower(`limit`),_status)
}
    }
    )
    }



    /**
     * Send an encrypted DM via NIP-17 gift wrapping.
     */
    @Throws(NuruNuruFfiException::class)override fun `sendDm`(`recipientHex`: kotlin.String, `content`: kotlin.String)
        =
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_send_dm(
        it, FfiConverterString.lower(`recipientHex`),FfiConverterString.lower(`content`),_status)
}
    }




    /**
     * Unfollow a user (publishes updated kind 3 contact list).
     */
    @Throws(NuruNuruFfiException::class)override fun `unfollowUser`(`targetPubkeyHex`: kotlin.String)
        =
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_unfollow_user(
        it, FfiConverterString.lower(`targetPubkeyHex`),_status)
}
    }




    /**
     * Verify NIP-05 identifier.
     */
    @Throws(NuruNuruFfiException::class)override fun `verifyNip05`(`nip05`: kotlin.String, `pubkeyHex`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_verify_nip05(
        it, FfiConverterString.lower(`nip05`),FfiConverterString.lower(`pubkeyHex`),_status)
}
    }
    )
    }



    /**
     * Zap a user's post.
     */
    @Throws(NuruNuruFfiException::class)override fun `zap`(`eventIdHex`: kotlin.String, `authorPubkeyHex`: kotlin.String, `amountSats`: kotlin.ULong, `message`: kotlin.String?)
        =
    callWithPointer {
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_method_nurunuruclient_zap(
        it, FfiConverterString.lower(`eventIdHex`),FfiConverterString.lower(`authorPubkeyHex`),FfiConverterULong.lower(`amountSats`),FfiConverterOptionalString.lower(`message`),_status)
}
    }







    companion object

}

/**
 * @suppress
 */
public object FfiConverterTypeNuruNuruClient: FfiConverter<NuruNuruClient, Pointer> {

    override fun lower(value: NuruNuruClient): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): NuruNuruClient {
        return NuruNuruClient(value)
    }

    override fun read(buf: ByteBuffer): NuruNuruClient {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: NuruNuruClient) = 8UL

    override fun write(value: NuruNuruClient, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}



/**
 * NIP-58 Badge Award.
 */
data class FfiBadgeAward (
    var `badgeId`: kotlin.String,
    var `awardEventId`: kotlin.String,
    var `awardPubkey`: kotlin.String
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiBadgeAward: FfiConverterRustBuffer<FfiBadgeAward> {
    override fun read(buf: ByteBuffer): FfiBadgeAward {
        return FfiBadgeAward(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiBadgeAward) = (
            FfiConverterString.allocationSize(value.`badgeId`) +
            FfiConverterString.allocationSize(value.`awardEventId`) +
            FfiConverterString.allocationSize(value.`awardPubkey`)
    )

    override fun write(value: FfiBadgeAward, buf: ByteBuffer) {
            FfiConverterString.write(value.`badgeId`, buf)
            FfiConverterString.write(value.`awardEventId`, buf)
            FfiConverterString.write(value.`awardPubkey`, buf)
    }
}



/**
 * Relay pool connection statistics.
 */
data class FfiConnectionStats (
    var `connectedRelays`: kotlin.UInt,
    var `totalRelays`: kotlin.UInt
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiConnectionStats: FfiConverterRustBuffer<FfiConnectionStats> {
    override fun read(buf: ByteBuffer): FfiConnectionStats {
        return FfiConnectionStats(
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: FfiConnectionStats) = (
            FfiConverterUInt.allocationSize(value.`connectedRelays`) +
            FfiConverterUInt.allocationSize(value.`totalRelays`)
    )

    override fun write(value: FfiConnectionStats, buf: ByteBuffer) {
            FfiConverterUInt.write(value.`connectedRelays`, buf)
            FfiConverterUInt.write(value.`totalRelays`, buf)
    }
}



/**
 * DM Conversation summary.
 */
data class FfiDmConversation (
    var `partnerPubkey`: kotlin.String,
    var `lastMessage`: kotlin.String,
    var `lastMessageAt`: kotlin.ULong
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiDmConversation: FfiConverterRustBuffer<FfiDmConversation> {
    override fun read(buf: ByteBuffer): FfiDmConversation {
        return FfiDmConversation(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: FfiDmConversation) = (
            FfiConverterString.allocationSize(value.`partnerPubkey`) +
            FfiConverterString.allocationSize(value.`lastMessage`) +
            FfiConverterULong.allocationSize(value.`lastMessageAt`)
    )

    override fun write(value: FfiDmConversation, buf: ByteBuffer) {
            FfiConverterString.write(value.`partnerPubkey`, buf)
            FfiConverterString.write(value.`lastMessage`, buf)
            FfiConverterULong.write(value.`lastMessageAt`, buf)
    }
}



/**
 * Encrypted DM message.
 */
data class FfiDmMessage (
    var `eventId`: kotlin.String,
    var `senderPubkey`: kotlin.String,
    var `content`: kotlin.String,
    var `createdAt`: kotlin.ULong
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiDmMessage: FfiConverterRustBuffer<FfiDmMessage> {
    override fun read(buf: ByteBuffer): FfiDmMessage {
        return FfiDmMessage(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: FfiDmMessage) = (
            FfiConverterString.allocationSize(value.`eventId`) +
            FfiConverterString.allocationSize(value.`senderPubkey`) +
            FfiConverterString.allocationSize(value.`content`) +
            FfiConverterULong.allocationSize(value.`createdAt`)
    )

    override fun write(value: FfiDmMessage, buf: ByteBuffer) {
            FfiConverterString.write(value.`eventId`, buf)
            FfiConverterString.write(value.`senderPubkey`, buf)
            FfiConverterString.write(value.`content`, buf)
            FfiConverterULong.write(value.`createdAt`, buf)
    }
}



/**
 * Result of parse_keys.
 */
data class FfiParsedKeys (
    var `secretKeyHex`: kotlin.String,
    var `publicKeyHex`: kotlin.String
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiParsedKeys: FfiConverterRustBuffer<FfiParsedKeys> {
    override fun read(buf: ByteBuffer): FfiParsedKeys {
        return FfiParsedKeys(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiParsedKeys) = (
            FfiConverterString.allocationSize(value.`secretKeyHex`) +
            FfiConverterString.allocationSize(value.`publicKeyHex`)
    )

    override fun write(value: FfiParsedKeys, buf: ByteBuffer) {
            FfiConverterString.write(value.`secretKeyHex`, buf)
            FfiConverterString.write(value.`publicKeyHex`, buf)
    }
}



/**
 * Scored post entry from the recommendation engine.
 */
data class FfiScoredPost (
    var `eventId`: kotlin.String,
    var `pubkey`: kotlin.String,
    var `score`: kotlin.Double,
    var `createdAt`: kotlin.ULong
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiScoredPost: FfiConverterRustBuffer<FfiScoredPost> {
    override fun read(buf: ByteBuffer): FfiScoredPost {
        return FfiScoredPost(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: FfiScoredPost) = (
            FfiConverterString.allocationSize(value.`eventId`) +
            FfiConverterString.allocationSize(value.`pubkey`) +
            FfiConverterDouble.allocationSize(value.`score`) +
            FfiConverterULong.allocationSize(value.`createdAt`)
    )

    override fun write(value: FfiScoredPost, buf: ByteBuffer) {
            FfiConverterString.write(value.`eventId`, buf)
            FfiConverterString.write(value.`pubkey`, buf)
            FfiConverterDouble.write(value.`score`, buf)
            FfiConverterULong.write(value.`createdAt`, buf)
    }
}



/**
 * Parsed user profile (NIP-01 kind 0 metadata).
 */
data class FfiUserProfile (
    var `name`: kotlin.String,
    var `displayName`: kotlin.String,
    var `about`: kotlin.String,
    var `picture`: kotlin.String,
    var `nip05`: kotlin.String,
    var `lud16`: kotlin.String,
    var `pubkey`: kotlin.String
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiUserProfile: FfiConverterRustBuffer<FfiUserProfile> {
    override fun read(buf: ByteBuffer): FfiUserProfile {
        return FfiUserProfile(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiUserProfile) = (
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`displayName`) +
            FfiConverterString.allocationSize(value.`about`) +
            FfiConverterString.allocationSize(value.`picture`) +
            FfiConverterString.allocationSize(value.`nip05`) +
            FfiConverterString.allocationSize(value.`lud16`) +
            FfiConverterString.allocationSize(value.`pubkey`)
    )

    override fun write(value: FfiUserProfile, buf: ByteBuffer) {
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`displayName`, buf)
            FfiConverterString.write(value.`about`, buf)
            FfiConverterString.write(value.`picture`, buf)
            FfiConverterString.write(value.`nip05`, buf)
            FfiConverterString.write(value.`lud16`, buf)
            FfiConverterString.write(value.`pubkey`, buf)
    }
}





sealed class NuruNuruFfiException(message: String): kotlin.Exception(message) {

        class RuntimeException(message: String) : NuruNuruFfiException(message)

        class KeyException(message: String) : NuruNuruFfiException(message)

        class EngineException(message: String) : NuruNuruFfiException(message)


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<NuruNuruFfiException> {
        override fun lift(error_buf: RustBuffer.ByValue): NuruNuruFfiException = FfiConverterTypeNuruNuruFfiError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeNuruNuruFfiError : FfiConverterRustBuffer<NuruNuruFfiException> {
    override fun read(buf: ByteBuffer): NuruNuruFfiException {

            return when(buf.getInt()) {
            1 -> NuruNuruFfiException.RuntimeException(FfiConverterString.read(buf))
            2 -> NuruNuruFfiException.KeyException(FfiConverterString.read(buf))
            3 -> NuruNuruFfiException.EngineException(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }

    }

    override fun allocationSize(value: NuruNuruFfiException): ULong {
        return 4UL
    }

    override fun write(value: NuruNuruFfiException, buf: ByteBuffer) {
        when(value) {
            is NuruNuruFfiException.RuntimeException -> {
                buf.putInt(1)
                Unit
            }
            is NuruNuruFfiException.KeyException -> {
                buf.putInt(2)
                Unit
            }
            is NuruNuruFfiException.EngineException -> {
                buf.putInt(3)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiUserProfile: FfiConverterRustBuffer<FfiUserProfile?> {
    override fun read(buf: ByteBuffer): FfiUserProfile? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiUserProfile.read(buf)
    }

    override fun allocationSize(value: FfiUserProfile?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiUserProfile.allocationSize(value)
        }
    }

    override fun write(value: FfiUserProfile?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiUserProfile.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiBadgeAward: FfiConverterRustBuffer<List<FfiBadgeAward>> {
    override fun read(buf: ByteBuffer): List<FfiBadgeAward> {
        val len = buf.getInt()
        return List<FfiBadgeAward>(len) {
            FfiConverterTypeFfiBadgeAward.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiBadgeAward>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiBadgeAward.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiBadgeAward>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiBadgeAward.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiDmConversation: FfiConverterRustBuffer<List<FfiDmConversation>> {
    override fun read(buf: ByteBuffer): List<FfiDmConversation> {
        val len = buf.getInt()
        return List<FfiDmConversation>(len) {
            FfiConverterTypeFfiDmConversation.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiDmConversation>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiDmConversation.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiDmConversation>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiDmConversation.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiDmMessage: FfiConverterRustBuffer<List<FfiDmMessage>> {
    override fun read(buf: ByteBuffer): List<FfiDmMessage> {
        val len = buf.getInt()
        return List<FfiDmMessage>(len) {
            FfiConverterTypeFfiDmMessage.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiDmMessage>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiDmMessage.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiDmMessage>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiDmMessage.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiScoredPost: FfiConverterRustBuffer<List<FfiScoredPost>> {
    override fun read(buf: ByteBuffer): List<FfiScoredPost> {
        val len = buf.getInt()
        return List<FfiScoredPost>(len) {
            FfiConverterTypeFfiScoredPost.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiScoredPost>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiScoredPost.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiScoredPost>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiScoredPost.write(it, buf)
        }
    }
}
        /**
         * Convert an npub bech32 to pubkey hex.
         */
    @Throws(NuruNuruFfiException::class) fun `npubToHex`(`npub`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_func_npub_to_hex(
        FfiConverterString.lower(`npub`),_status)
}
    )
    }


        /**
         * Parse a Nostr secret key (hex or nsec) and return (hex, pubkey_hex).
         * Used as a workaround for nostr-sdk-jvm missing Android ARM64 binaries.
         */
    @Throws(NuruNuruFfiException::class) fun `parseKeys`(`input`: kotlin.String): FfiParsedKeys {
            return FfiConverterTypeFfiParsedKeys.lift(
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_func_parse_keys(
        FfiConverterString.lower(`input`),_status)
}
    )
    }


        /**
         * Convert a pubkey hex to npub bech32.
         */
    @Throws(NuruNuruFfiException::class) fun `pubkeyToNpub`(`pubkeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(NuruNuruFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_nurunuru_ffi_fn_func_pubkey_to_npub(
        FfiConverterString.lower(`pubkeyHex`),_status)
}
    )
    }
